import { LanguageLabel } from 'src/app/model/language-label.model';

export const texts: LanguageLabel[] = [
  {
    // Croatian
    landingPageTitle: 'Priroda, netaknuta',
    landingPageSubTitle:
      'Dobrodošli u Slapove Zrmanje, mjesto za odmor i avanturu.',
    landingPageReservationTitle: 'Rezervacije',
    landingPageReservationCamp: 'Kamp',
    landingPageReservationRooms: 'Sobe',
    landingPageReservationApartments: 'Apartmani',
    landingPageBurgerGallery: 'Galerija',
    landingPageBurgerContact: 'Kontakt',
    landingPageBurgerLanguage: 'Jezik',
    landingPageBurgerLanguageCroatian: 'Hrvatski',
    landingPageBurgerLanguageEnglish: 'Engleski',
    landingPageBurgerLanguageGerman: 'Njemački',
    landingPageAboutUsTitle: 'O NAMA',
    landingPageCopyrightText: 'Autorska prava',
    inputNameText: 'Naziv',
    inputFirstNameText: 'Ime',
    inputLastNameText: 'Prezime',
    inputEmailText: 'Email adresa',
    inputMessageText: 'Poruka',
    dropdownGuestsLabel: 'Gosti',
    dropdownGuestsInitialLine: 'Odaberite goste',
    dropdownGuestsTitle1: 'Odrasli',
    dropdownGuestsTitle2: 'Djeca',
    dropdownGuestsTitle3: 'Dojenčad',
    dropdownGuestsTitle4: 'Ljubimci',
    dropdownGuestsSubtitle1: 'Dobi 13+',
    dropdownGuestsSubtitle2: 'Dobi 2-12',
    dropdownGuestsSubtitle3: 'Ispod 2',
    dropdownGuestsSubtitle4: '',
    dropdownLodgingLabel: 'Smještaj',
    dropdownLodgingInitialLine: 'Odaberite smještaj',
    dropdownLodgingTitle1: 'Šator',
    dropdownLodgingTitle2: 'Karavan',
    dropdownLodgingTitle3: 'Automobil',
    dropdownLodgingTitle4: 'Vreća za spavanje',
    dropdownLodgingSubtitle1: '',
    dropdownLodgingSubtitle2: '',
    dropdownLodgingSubtitle3: '',
    dropdownLodgingSubtitle4: '',
    checkBoxTitle: 'Korisćenje struje',
    checkAvailabilityButtonText: 'Provjera Dostupnosti',
    calendarLabel: 'Prijava & Odjava',
    calendarDays: 'Po, Ut, Sr, Če, Pe, Su, Ne',
    calendarMonths:
      'Januar, Februar, Mart, April, Maj, Jun, Jul, Avgust, Septembar, Oktobar, Novembar, Decembar',
    calculator: 'Pregled cene:',
    calculateButtonText: 'Izračunaj',
    totalText: 'Ukupno:',
    dropdownRoomLodgingTitle1: 'Soba 1',
    dropdownRoomLodgingTitle2: 'Soba 2',
    dropdownRoomLodgingTitle3: 'Soba 3',
    dropdownRoomLodgingSubtitle1: '2 osobe',
    dropdownRoomLodgingSubtitle2: '2 osobe',
    dropdownRoomLodgingSubtitle3: '3 osobe',
    dropdownApartmentLodgingTitle1: 'Apartman 1',
    dropdownApartmentLodgingTitle2: 'Apartman 2',
    dropdownApartmentLodgingTitle3: 'Apartman 3',
    dropdownApartmentLodgingSubtitle1: '5 osobe',
    dropdownApartmentLodgingSubtitle2: '4 osobe',
    dropdownApartmentLodgingSubtitle3: '4 osobe',
    restaurant: 'RESTORAN',
    accommodations: 'SMEŠTAJI',
    activities: 'AKTIVNOSTI',
    getInTouch: 'STUPITE U KONTAKT',
    workingMonths: 'Radno vreme od 28 Aprila do 1 Septembra',
    workingHours: 'od 9h do 21h',
    country: 'Hrvatska',
    sendButtonText: 'Pošalji',
  },
  {
    // English
    landingPageTitle: 'Nature, Untouched',
    landingPageSubTitle:
      'Welcome to Slapovi Zrmanje, a place for rest and adventure.',
    landingPageReservationTitle: 'Reservations',
    landingPageReservationCamp: 'Camp',
    landingPageReservationRooms: 'Rooms',
    landingPageReservationApartments: 'Apartments',
    landingPageBurgerGallery: 'Gallery',
    landingPageBurgerContact: 'Contact',
    landingPageBurgerLanguage: 'Language',
    landingPageBurgerLanguageCroatian: 'Croatian',
    landingPageBurgerLanguageEnglish: 'English',
    landingPageBurgerLanguageGerman: 'German',
    landingPageAboutUsTitle: 'ABOUT US',
    landingPageCopyrightText: 'Copyright',
    inputNameText: 'Name',
    inputFirstNameText: 'First Name',
    inputLastNameText: 'Last Name',
    inputEmailText: 'Email Address',
    inputMessageText: 'Message',
    dropdownGuestsLabel: 'Guests',
    dropdownGuestsInitialLine: 'Choose guests',
    dropdownGuestsTitle1: 'Adults',
    dropdownGuestsTitle2: 'Children',
    dropdownGuestsTitle3: 'Infants',
    dropdownGuestsTitle4: 'Pets',
    dropdownGuestsSubtitle1: 'Age 13+',
    dropdownGuestsSubtitle2: 'Ages 2-12',
    dropdownGuestsSubtitle3: 'Under 2',
    dropdownGuestsSubtitle4: '',
    dropdownLodgingLabel: 'Lodging',
    dropdownLodgingInitialLine: 'Choose lodging',
    dropdownLodgingTitle1: 'Tent',
    dropdownLodgingTitle2: 'Caravan',
    dropdownLodgingTitle3: 'Car',
    dropdownLodgingTitle4: 'Sleeping Bag',
    dropdownLodgingSubtitle1: '',
    dropdownLodgingSubtitle2: '',
    dropdownLodgingSubtitle3: '',
    dropdownLodgingSubtitle4: '',
    checkBoxTitle: 'Power Supply',
    checkAvailabilityButtonText: 'Check Availability',
    calendarLabel: 'Check-In & Checkout',
    calendarDays: 'Mo, Tu, We, Th, Fr, Sa, Su',
    calendarMonths:
      'January, February, March, April, May, June, July, August, September, October, November, December',
    calculator: 'Price preview:',
    calculateButtonText: 'Calculate',
    totalText: 'In total:',
    dropdownRoomLodgingTitle1: 'Room 1',
    dropdownRoomLodgingTitle2: 'Room 2',
    dropdownRoomLodgingTitle3: 'Room 3',
    dropdownRoomLodgingSubtitle1: '2 Persons',
    dropdownRoomLodgingSubtitle2: '2 Persons',
    dropdownRoomLodgingSubtitle3: '3 Persons',
    dropdownApartmentLodgingTitle1: 'Apartment 1',
    dropdownApartmentLodgingTitle2: 'Apartment 2',
    dropdownApartmentLodgingTitle3: 'Apartment 3',
    dropdownApartmentLodgingSubtitle1: '5 Persons',
    dropdownApartmentLodgingSubtitle2: '4 Persons',
    dropdownApartmentLodgingSubtitle3: '4 Persons',
    restaurant: 'RESTAURANT',
    accommodations: 'ACCOMMODATIONS',
    activities: 'ACTIVITIES',
    getInTouch: 'GET IN TOUCH',
    workingMonths: 'Working time from April 28 to September 1',
    workingHours: 'from 9AM to 9PM',
    country: 'Croatia',
    sendButtonText: 'Send',
  },
  {
    // German
    landingPageTitle: 'Natur, Unberührt',
    landingPageSubTitle:
      'Willkommen in Slapovi Zrmanje, einem Ort der Ruhe und des Abenteuers.',
    landingPageReservationTitle: 'Reservierungen',
    landingPageReservationCamp: 'Lager',
    landingPageReservationRooms: 'Räume',
    landingPageReservationApartments: 'Wohnungen',
    landingPageBurgerGallery: 'Galerie',
    landingPageBurgerContact: 'Kontakt',
    landingPageBurgerLanguage: 'Sprache',
    landingPageBurgerLanguageCroatian: 'Kroatisch',
    landingPageBurgerLanguageEnglish: 'Englisch',
    landingPageBurgerLanguageGerman: 'Deutsch',
    landingPageAboutUsTitle: 'ÜBER UNS',
    landingPageCopyrightText: 'Urheberrechte',
    inputNameText: 'Name',
    inputFirstNameText: 'Vorname',
    inputLastNameText: 'Familienname',
    inputEmailText: 'E-Mail-Adresse',
    inputMessageText: 'Nachricht',
    dropdownGuestsLabel: 'Gäste',
    dropdownGuestsInitialLine: 'Wählen Sie Gäste aus',
    dropdownGuestsTitle1: 'Erwachsene',
    dropdownGuestsTitle2: 'Kinder',
    dropdownGuestsTitle3: 'Kleinkinder',
    dropdownGuestsTitle4: 'Haustiere',
    dropdownGuestsSubtitle1: 'Alter 13+',
    dropdownGuestsSubtitle2: 'Alter 2-12',
    dropdownGuestsSubtitle3: 'Unter 2',
    dropdownGuestsSubtitle4: '',
    dropdownLodgingLabel: 'Unterkunft',
    dropdownLodgingInitialLine: 'Wählen Sie eine Unterkunft',
    dropdownLodgingTitle1: 'Zelt',
    dropdownLodgingTitle2: 'Wohnwagen',
    dropdownLodgingTitle3: 'Auto',
    dropdownLodgingTitle4: 'Schlafsack',
    dropdownLodgingSubtitle1: '',
    dropdownLodgingSubtitle2: '',
    dropdownLodgingSubtitle3: '',
    dropdownLodgingSubtitle4: '',
    checkBoxTitle: 'Stromversorgung',
    checkAvailabilityButtonText: 'Verfügbarkeit Prüfen',
    calendarLabel: 'Einchecken & Auschecken',
    calendarDays: 'Mo, Di, Mi, Do, Fr, Sa, So',
    calendarMonths:
      'Januar, Februar, März, April, Mai, Juni, Juli, August, September, Oktober, November, Dezember',
    calculator: 'Preisvorschau:',
    calculateButtonText: 'Berechnung',
    totalText: 'In Summe:',
    dropdownRoomLodgingTitle1: 'Zimmer 1',
    dropdownRoomLodgingTitle2: 'Zimmer 2',
    dropdownRoomLodgingTitle3: 'Zimmer 3',
    dropdownRoomLodgingSubtitle1: '2 Personen',
    dropdownRoomLodgingSubtitle2: '2 Personen',
    dropdownRoomLodgingSubtitle3: '3 Personen',
    dropdownApartmentLodgingTitle1: 'Wohnung 1',
    dropdownApartmentLodgingTitle2: 'Wohnung 2',
    dropdownApartmentLodgingTitle3: 'Wohnung 3',
    dropdownApartmentLodgingSubtitle1: '5 Personen',
    dropdownApartmentLodgingSubtitle2: '4 Personen',
    dropdownApartmentLodgingSubtitle3: '4 Personen',
    restaurant: 'RESTAURANT',
    accommodations: 'UNTERKÜNFTE',
    activities: 'AKTIVITÄTEN',
    getInTouch: 'IN KONTAKT KOMMEN',
    workingMonths: 'Arbeitszeit vom 28. April bis 1. September',
    workingHours: 'von 9 bis 21 Uhr',
    country: 'Kroatien',
    sendButtonText: 'Schicken',
  },
];
